name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    name: Continuous Integration
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 10.6.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Unit Test
        run: pnpm test

      - name: Functional Tests
        run: pnpm test:functional

      - name: Build
        run: pnpm build